# Generated by Django 3.1.1 on 2020-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
                ('room', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
    ]
