# Generated by Django 3.1.1 on 2020-09-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='room',
            new_name='env',
        ),
    ]
