# Generated by Django 3.1.1 on 2020-09-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
