# Generated by Django 3.1.1 on 2020-09-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0006_auto_20200904_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_default.project')),
            ],
        ),
    ]
